spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_batch_fetch_size: 100
      hibernate.jdbc.batch_size: 100
      hibernate.order_inserts: false
      hibernate.order_updates: true

---
spring.config.activate.on-profile: local

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show_sql: true

storage:
  datasource:
    core:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?reWriteBatchedInserts=true
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      minimum-idle: 0
      idle-timeout: 240000

---
spring.config.activate.on-profile: dev

storage:
  datasource:
    core:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?reWriteBatchedInserts=true
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      minimum-idle: 0
      idle-timeout: 240000

---
spring.config.activate.on-profile: test

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true

storage:
  datasource:
    core:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:core;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      data-source-properties:
        rewriteBatchedStatements: true
